import React from 'react';
import {View, Text, ScrollView, StyleSheet, TouchableOpacity} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';
import {normalize} from '../dimension';
import {black, grey, white} from '../assets/Colors';

export default function Terms(props) {
  return (
    <View style={styles.mainContainer}>
      <View style={styles.header}>
        <TouchableOpacity onPress = {() => {props.navigation.goBack()}}>
        <Icon name={'arrow-back'} size={normalize(30)} color={white} />
        </TouchableOpacity>
        
        <Text style={styles.lionsgateLogo}>Lionsgate Play</Text>
      </View>
      <ScrollView contentContainerStyle={styles.scrollview}>
        <Text style={styles.mainHeading}>TERMS OF SERVICE</Text>
        <Text style={styles.heading}>1. Who We Are</Text>
        <Text style={styles.content}>
          We are Lions Gate Play LLP having a place of business at 502, Crest
          Mukta, Fun Republic Lane, Off New Link Road, Andheri (West), Mumbai
          400058 (“Lionsgate”, “us”, “our” or “we”).
        </Text>
        <Text style={styles.heading}>2. Introduction</Text>
        <Text style={styles.content}>
          These Terms of Service govern the relationship between you and us when
          you access or use the Lionsgate subscription video-on-demand service
          (the “Service”), the website located
          at https://lionsgateplay.com associated with the Service (the “Site”),
          any mobile and/or smart TV app associated with the Service (the
          “Apps”), and/or any of the features or downloads that are made
          available through or interact with the Service or Site (the
          “Features”).
        </Text>
        <Text style={styles.content}>
          This Terms of Service along with the privacy policy available
          at https://www.lionsgateplay.com/privacypolicy (“Privacy Policy”),
          which is an integral part of the Terms of Service is a binding
          agreement between Lionsgate and you for the use of the Services. This
          Terms of Service is an electronic record under Information Technology
          Act, 2000 as amended and the relevant rules made thereunder as
          applicable and the amended provisions pertaining to electronic records
          in various statutes under applicable Indian laws. This electronic
          record is generated by a computer system and does not require any
          physical or digital signatures.
        </Text>
        <Text style={styles.content}>
          Please read these Terms of Service carefully. By using the Service,
          the Site, the Apps, and/or the Features, and (where applicable) by
          clicking “Accept and Continue” or “Continue," you are agreeing to
          these Terms of Service, which form a binding agreement between you and
          us. If you do not agree to these Terms of Service, please do not use
          the Lionsgate Services. This Terms of Service was last updated on
          January 28, 2021. We will periodically update this Terms of Service so
          please check back for updates.
        </Text>
        <Text style={styles.heading}>3. Terminology</Text>
        <Text style={styles.content}>
          In these Terms of Service, you will see capitalised words and phrases.
          These capitalised words and phrases are defined terms – this means
          that they have specific meanings. The first time a defined term is
          used, you will see it in brackets and in bold (for example where we’ve
          defined “Service”, “Site”, “Apps” and “Features” in the section
          above).
        </Text>
        <Text style={styles.content}>In these Terms of Service:</Text>
        <Text style={styles.content}>
          a) Where we want to refer to the Service, the Site, the Apps, and the
          Features all together, we will say the “Lionsgate Services”.b)
          Otherwise, we will refer to things individually using the relevant
          defined terms.
        </Text>
        <Text style={styles.heading}>4. Other Important Terms</Text>
        <Text style={styles.content}>
          Our Privacy Policy sets out the terms on which we process any personal
          data we collect from you or that you provide to us via the Lionsgate
          Services. It also includes our policy on cookies.
        </Text>
        <Text style={styles.content}>
          If you access the Lionsgate Services via an authorized third party
          Service provider (“Distributor”) there may be separate Terms of
          Service that apply to the use of that Distributor’s platform, service
          or applications. We have no knowledge of or control over these third
          party terms and you accept them at your own risk. Our Terms of Service
          will still apply however to your use of the Lionsgate Services.
        </Text>
        <Text style={styles.heading}>6. Changes to the Lionsgate Services</Text>
        <Text style={styles.content}>
          Lionsgate reserves the right to change, alter, discontinue, enhance,
          add or delete any aspect of the Lionsgate Services at any time. We
          will notify you of any material changes to the Lionsgate Services or
          our ability to provide you access to them. Your continued use of the
          Lionsgate Services after we have given you notice of such changes will
          be taken as your acceptance of the changes made.
        </Text>

        <Text style = {styles.heading}>
          8. Geographic Location 
          
          </Text>
          <Text style = {styles.content}>
          The Lionsgate Services and Content being
          offered to you on subscribing are limited to certain geographic
          territories only. We may use technologies to verify your geographic
          location in order to provide uninterrupted access to you of the
          Content and Lionsgate Services, you shall not use disguising
          mechanisms (including but not limited to VPN) and technology to
          surpass such measures taken by us to verify your location
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: black,
  },
  header: {
    backgroundColor: '#1A1A1C',
    flexDirection: 'row',
    paddingLeft: normalize(10),
    alignItems: 'center',
  },
  lionsgateLogo: {
    color: '#ccc',
    fontSize: normalize(18),
    marginLeft: normalize(30),
    marginVertical: normalize(10),
  },
  scrollview: {
    paddingHorizontal: normalize(20),
    paddingTop: normalize(20),
  },
  mainHeading: {
    fontSize: normalize(16),
    fontWeight: 'bold',
    color: white,
    alignSelf: 'center',
  },
  heading: {
    color: white,
    fontSize: normalize(22),
    fontWeight: 'bold',
    marginVertical: normalize(10),
  },
  content: {
    color: '#ADADAD',
    fontSize: normalize(12),
    marginVertical: normalize(10),
    textAlign: "justify"
  },
});
